version: "3.9"
services:  
  mysql:
    image: "mysql"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: dcap
      MYSQL_DATABASE: dcap
      MYSQL_USER: dcap
      MYSQL_PASSWORD: dcap
    volumes:
      - "./dcap/dbSchema/dcapSchema.sql:/docker-entrypoint-initdb.d/1.sql"
    expose:
      - '3306'

  dcap:
    build:
      context: './dcap'
      dockerfile: Dockerfile
    expose:
      - '8989'
    ports:
      - "8989:8989"
    environment:
      WAIT_HOSTS: mysql:3306
    depends_on:
      - "mysql"